export const skills = {
  language: ["javascript", "typescript", "php", "python", "graphql", "cpp"],
  framework: [
    "react",
    "nextjs",
    "django",
    "astro",
    "express",
    "phalcon",
    "codeigniter",
    "laravel",
    "elysiajs",
  ],
  library: [
    "svelte",
    "tanstackquery",
    "redux",
    "mobx",
    "antd",
    "tailwind",
    "bootstrap",
    "jquery",
    "styled",
    "aggrid",
    "apollo",
    "jest",
    "storybook",
  ],
  preprocessor: ["sass", "less"],
  bundler: ["webpack", "vite"],
  database: ["mysql", "postgres"],
  runtime: ["nodejs", "deno", "bun"],
  server: ["apache", "nginx"],
  container: ["docker"],
  cms: ["strapi", "payload", "directus"],
};

export const timeline = [
  {
    date: "DECEMBER 2022 - CURRENT",
    title: "Senior Software Engineer",
    subtitle: "Strativ, Dhaka, Bangladesh",
    skills: [
      "typescript",
      "react",
      "nextjs",
      "redux",
      "tanstackquery",
      "strapi",
      "payload",
      "directus",
      "tailwind",
      "nginx",
      "vite",
      "antd",
      "docker",
    ],
    description: "-",
    jobs: [
      "Spearheaded front-end development of Resemolnet, an AI-powered SaaS booking management system, successfully launching the product and gaining traction in a competitive market.",
      "Developed javascript widget to integrate the booking system with any website, reducing client integration time by 80%.",
      "Implemented multilingual support on the moresailing.se website and integrated automated content translation, expanding the potential customer base to 6+ language markets and reduced time for managing multilingual content  by 90%.",
      "Integrated Stripe payment and subscription services using API and SDK.",
      "Implemented Mailchimp audience capture and journey trigger using API ",
      "Managed multiple projects simultaneously and conducted interviews and assessments.",
    ],
  },
  {
    date: "JANUARY 2022 - NOVEMBER 2022",
    title: "Software Engineer",
    subtitle: "Strativ, Dhaka, Bangladesh",
    skills: [
      "typescript",
      "graphql",
      "nextjs",
      "apollo",
      "tailwind",
      "strapi",
      "postgres",
      "docker",
    ],
    description: "",
    jobs: [
      "Developed a wordpress plugin using Javascript for end-to-end email encryption with OpenPGP ensuring complete security for sensitive data.",
      "Designed a headless CMS solution with Strapi and Next.js. Ensured full type safety using GraphQL and CodeGen.",
      "Rebuilt the Moresailing website from WordPress to a Next.js-Strapi headless CMS stack, achieving 150% overall  performance improvements and better SEO.",
    ],
  },
  {
    date: "DECEMBER 2021 - CURRENT (REMOTE)",
    title: "Software Developer",
    subtitle: "Texada Software, ON, Canada",
    skills: [
      "javascript",
      "typescript",
      "php",
      "python",
      "react",
      "phalcon",
      "codeigniter",
      "redux",
      "mobx",
      "aggrid",
      "storybook",
      "jest",
      "django",
      "mysql",
      "nginx",
      "webpack",
      "sass",
      "docker",
    ],
    jobs: [
      "Contributed to the development and maintenance of new features for rental management and e-commerce products using react in frontend.",
      "Created APIs for new features using PHP Phalcon and Python Django ",
      "Demonstrated adaptability by working effectively across multiple tech stacks in a versatile development environment.",
      "Improved code quality by writing comprehensive test cases",
      "Developed automatic product description generator using generative ai",
      "Built complex financial data grids with AgGrid, enhancing data visualization and analysis capabilities for end-users.",
      "Fostered efficient team collaboration in a 100% remote working environment.",
    ],
  },

  {
    date: "MAY 2021 - DECEMBER 2021",
    title: "Junior Software Engineer",
    subtitle: "Strativ, Dhaka, Bangladesh",
    skills: ["javascript", "react", "antd", "redux", "styled"],
    jobs: [
      " Served as the front-end developer for Ahoy Booking Systems, worked in development of critical accounting, booking, supplements, ticketing, pricing, payment, and third-party booking manager API integration.",
      "Developed innovative complex frontend features for data visualization and management.",
    ],
  },
];
