export const skills = {
  language: ["javascript", "typescript", "php", "graphql", "python", "cpp"],
  framework: [
    "react",
    "nextjs",
    "astro",
    "express",
    "phalcon",
    "codeigniter",
    "laravel",
    "elysiajs",
  ],
  library: [
    "svelte",
    "tanstackquery",
    "redux",
    "mobx",
    "antd",
    "tailwind",
    "bootstrap",
    "jquery",
    "styled",
    "aggrid",
    "apollo",
  ],
  preprocessor: ["sass", "less"],
  bundler: ["webpack", "vite"],
  database: ["mysql", "postgres"],
  runtime: ["nodejs", "deno", "bun"],
  server: ["apache", "nginx"],
  container: ["docker"],
  cms: ["strapi"],
};

export const logs = [
  {
    title: "Ahoy booking management system",
    subtitle: "Booking Management Systems",
    skills: ["javascript", "react", "antd", "redux", "styled"],
    description:
      "Ahoy stands as the booking management system originally developed for Moresailing, subsequently evolving into the foundational platform for the Resemolnet Multi-Tenant Booking Management System. Serving as a pivotal tool, Ahoy has streamlined the booking process for numerous customers, facilitating the planning of their sailing trips. This system has played a crucial role in enhancing the overall booking and management experience, leading to a notable increase in sales. To date, it has generated a revenue exceeding SEK 100 million. Ahoy encompasses all essential functionalities required for managing the entire booking flow of sailing excursions. Notably, it seamlessly integrates with a third-party booking manager API for yacht rentals. I took charge of the frontend development for Ahoy and have been responsible for its ongoing maintenance, including the implementation of new features.",
  },
  {
    title: "Resemolnet multi-Tenant booking management system",
    subtitle: "Booking Management Systems",
    skills: [
      "typescript",
      "react",
      "antd",
      "tanstackquery",
      "styled",
      "less",
      "vite",
    ],
    description:
      "Resemolnet stands as a multi-tenant Software as a Service (SaaS) booking management system, succeeding Ahoy in its capabilities. Unlike its predecessor, Resemolent boasts the capacity to manage various types of excursions. With a modular-based design, it can be easily tailored to meet the specific needs of individual customers. Powered by artificial intelligence, Resemolnet offers AI services such as a chatbot as a plug-and-play widget. Additionally, Resemolnet provides plug-and-play widgets for excursion searching and booking. I took the initiative to spearhead the frontend development of the Resemolnet project and subsequently assumed the role of frontend team lead. In this capacity, I have overseen the seamless development process and continuous integration/continuous deployment (CI/CD) for other developers. My responsibilities also extend to planning new features and improvements. Resemolnet has successfully replaced Ahoy and is outperforming its predecessor for Moresailing.",
  },
  {
    title: "Moresailing - Saailing for all",
    subtitle: "Booking Website",
    skills: [
      "typescript",
      "graphql",
      "nextjs",
      "apollo",
      "tailwind",
      "strapi",
      "postgres",
      "docker",
    ],
    description:
      "Moresailing was initially a WordPress website. I was tasked with the development of a new website using Strapi and Next.js. To enhance performance significantly, we incorporated Static Site Generation (SSG) and Server-Side Rendering (SSR) with Next.js on the frontend. The website now boasts robust multi-locale support, and content is efficiently translated utilizing artificial intelligence. In Strapi, we integrated a translation tool capable of utilizing custom providers to facilitate content translation. Throughout the project, our primary challenge was to seamlessly transition to the new design without compromising any SEO scores.",
  },
  {
    title: "Texada Web",
    subtitle: "Rental Platform",
    skills: [
      "typescript",
      "javascript",
      "react",
      "aggrid",
      "redux",
      "sass",
      "webpack",
      "nginx",
      "docker",
    ],
    description:
      "Texada Web, an integral component of the Texada Software platform, is a web-based product specifically tailored to address the intricacies of managing the logistics associated with transporting rental equipment and handling work orders related to service and maintenance. It mirrors the functionality of Texada SRM (Systematic Rental Management), which is a comprehensive business management software application crafted to manage the financial and logistical facets of rental/hire and service operations. In my role, I have assumed responsibility for the frontend development of new features within Texada Web, as well as the maintenance of the existing codebase. This involves ensuring the seamless integration of enhancements to optimize the performance and user experience of the application.",
  },
  {
    title: "Texada Gateway",
    subtitle: "Rental Ecoommerce Platform",
    skills: [
      "javascript",
      "react",
      "mobx",
      "aggrid",
      "php",
      "phalcon",
      "codeigniter",
      "mysql",
      "nginx",
      "webpack",
      "sass",
      "docker",
    ],
    description:
      "GateWay is a comprehensive web-based platform that serves as a self-service and reporting hub. It encompasses an administration panel, customer access portal, and an e-commerce website. This versatile platform empowers users to enhance business relationships by providing customers with the ability to browse, purchase, or rent equipment online, akin to popular online retailers like Amazon. As a Full Stack Developer, I am actively involved in the transition phase of this project. Currently, the backend is undergoing a transition from CodeIgniter to Phalcon. In this capacity, I am tasked with the maintenance of the existing codebase and the development of new features, ensuring a seamless and efficient transition for GateWay.",
  },
];
