export const skills = {
  language: ["javascript", "typescript", "php", "graphql", "python", "cpp"],
  framework: [
    "react",
    "nextjs",
    "astro",
    "express",
    "phalcon",
    "codeigniter",
    "laravel",
    "elysiajs",
  ],
  library: [
    "svelte",
    "tanstackquery",
    "redux",
    "mobx",
    "antd",
    "tailwind",
    "bootstrap",
    "jquery",
    "styled",
    "aggrid",
    "apollo",
  ],
  preprocessor: ["sass", "less"],
  bundler: ["webpack", "vite"],
  database: ["mysql", "postgres"],
  runtime: ["nodejs", "deno", "bun"],
  server: ["apache", "nginx"],
  container: ["docker"],
  cms: ["strapi"],
};

export const logs = [
  {
    title: "Gateway",
    subtitle: "Rental Ecoommerce Platform",
    skills: [
      "javascript",
      "react",
      "mobx",
      "php",
      "phalcon",
      "codeigniter",
      "mysql",
      "nginx",
      "webpack",
      "sass",
      "docker",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    title: "Texada Web",
    subtitle: "Heavy Equipment Rental Platform",
    skills: [
      "typescript",
      "javascript",
      "react",
      "aggrid",
      "redux",
      "sass",
      "webpack",
      "nginx",
      "docker",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    title: "Moresailing - Saailing for all",
    subtitle: "Booking Website",
    skills: [
      "typescript",
      "graphql",
      "nextjs",
      "apollo",
      "tailwind",
      "strapi",
      "postgres",
      "docker",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    title: "Resemolnet Multi-Tenant Booking Management System",
    subtitle: "Booking Management Systems",
    skills: [
      "typescript",
      "react",
      "antd",
      "tanstackquery",
      "styled",
      "less",
      "vite",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    title: "Ahoy booking management system",
    subtitle: "Booking Management Systems",
    skills: ["javascript", "react", "antd", "redux", "styled"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
];
